common:
    gh_ident: &GH_ID github
aww_snap:
    local: &SN_L !loc_join ['data_dir', 'gateway-configs.git']
    remote: !str_join ['ssh://', *GH_ID ,'/freifunk-mwu/gateway-configs.git']
    queue: !loc_join [*SN_L, 'queue.yaml']
    target: !loc_join [*SN_L, !var_join ['hostname']]
